/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BatchTokenIssuerInterface extends ethers.utils.Interface {
  functions: {
    "canImplementInterfaceForAddress(bytes32,address)": FunctionFragment;
    "batchIssueByPartition(address,bytes32[],address[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "canImplementInterfaceForAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchIssueByPartition",
    values: [string, BytesLike[], string[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "canImplementInterfaceForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchIssueByPartition",
    data: BytesLike
  ): Result;

  events: {};
}

export class BatchTokenIssuer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BatchTokenIssuerInterface;

  functions: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "canImplementInterfaceForAddress(bytes32,address)"(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    batchIssueByPartition(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "batchIssueByPartition(address,bytes32[],address[],uint256[])"(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  canImplementInterfaceForAddress(
    interfaceHash: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "canImplementInterfaceForAddress(bytes32,address)"(
    interfaceHash: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  batchIssueByPartition(
    token: string,
    partitions: BytesLike[],
    tokenHolders: string[],
    values: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "batchIssueByPartition(address,bytes32[],address[],uint256[])"(
    token: string,
    partitions: BytesLike[],
    tokenHolders: string[],
    values: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "canImplementInterfaceForAddress(bytes32,address)"(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    batchIssueByPartition(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "batchIssueByPartition(address,bytes32[],address[],uint256[])"(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "canImplementInterfaceForAddress(bytes32,address)"(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchIssueByPartition(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "batchIssueByPartition(address,bytes32[],address[],uint256[])"(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    canImplementInterfaceForAddress(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "canImplementInterfaceForAddress(bytes32,address)"(
      interfaceHash: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchIssueByPartition(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "batchIssueByPartition(address,bytes32[],address[],uint256[])"(
      token: string,
      partitions: BytesLike[],
      tokenHolders: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
