/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IAuthProviderInterface extends ethers.utils.Interface {
  functions: {
    "hasAuthenticated(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "hasAuthenticated",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "hasAuthenticated",
    data: BytesLike
  ): Result;

  events: {};
}

export class IAuthProvider extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IAuthProviderInterface;

  functions: {
    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  hasAuthenticated(
    addr: string,
    latestAcceptedTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasAuthenticated(address,uint256)"(
    addr: string,
    latestAcceptedTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    hasAuthenticated(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasAuthenticated(address,uint256)"(
      addr: string,
      latestAcceptedTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
