/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Homer } from "../Homer";

export class Homer__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Homer> {
    return super.deploy(overrides || {}) as Promise<Homer>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Homer {
    return super.attach(address) as Homer;
  }
  connect(signer: Signer): Homer__factory {
    return super.connect(signer) as Homer__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Homer {
    return new Contract(address, _abi, signerOrProvider) as Homer;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "skinColor",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "is2D",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061017c806100206000396000f3fe608060405234801561001057600080fd5b50600436106100445760e060020a600035046301ffc9a78114610049578063137588f21461008457806360c33c6014610101575b600080fd5b6100706004803603602081101561005f57600080fd5b5035600160e060020a031916610109565b604080519115158252519081900360200190f35b61008c610146565b6040805160208082528351818301528351919283929083019185019080838360005b838110156100c65781810151838201526020016100ae565b50505050905090810190601f1680156100f35780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b61007061014b565b6000600160e060020a0319821660e060020a6301ffc9a70214806101405750600160e060020a0319821660e160020a6339db5a4902145b92915050565b606090565b60009056fea165627a7a72305820a5f92ed29f167fbb849dae5981c2ded82261cf7951b5a83d0d056211d89d48b00029";
