/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IERC1400TokensChecker } from "../IERC1400TokensChecker";

export class IERC1400TokensChecker__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1400TokensChecker {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC1400TokensChecker;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "payload",
        type: "bytes",
      },
      {
        name: "partition",
        type: "bytes32",
      },
      {
        name: "operator",
        type: "address",
      },
      {
        name: "from",
        type: "address",
      },
      {
        name: "to",
        type: "address",
      },
      {
        name: "value",
        type: "uint256",
      },
      {
        name: "data",
        type: "bytes",
      },
      {
        name: "operatorData",
        type: "bytes",
      },
    ],
    name: "canTransferByPartition",
    outputs: [
      {
        name: "",
        type: "bytes1",
      },
      {
        name: "",
        type: "bytes32",
      },
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
