/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Simpson } from "../Simpson";

export class Simpson__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Simpson {
    return new Contract(address, _abi, signerOrProvider) as Simpson;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "skinColor",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "is2D",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
